# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.response <- function(distribution, parameter, treatment) {
    .Call('_artool_response', PACKAGE = 'artool', distribution, parameter, treatment)
}

.restricted <- function(number_of_subjects, w, procedure, p, distribution, parameter) {
    .Call('_artool_restricted', PACKAGE = 'artool', number_of_subjects, w, procedure, p, distribution, parameter)
}

.simulate_restricted <- function(number_of_simulations, number_of_subjects, w, procedure, p, distribution, parameter) {
    .Call('_artool_simulate_restricted', PACKAGE = 'artool', number_of_simulations, number_of_subjects, w, procedure, p, distribution, parameter)
}

.t_test <- function(treatment, response, alpha = 0.05) {
    .Call('_artool_t_test', PACKAGE = 'artool', treatment, response, alpha)
}

.anova_test <- function(treatment, response, K, alpha = 0.05) {
    .Call('_artool_anova_test', PACKAGE = 'artool', treatment, response, K, alpha)
}

