# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

restricted <- function(number_of_subjects, w, procedure, p, distribution, parameter) {
    .Call('artool_restricted', PACKAGE = 'artool', number_of_subjects, w, procedure, p, distribution, parameter)
}

t_test <- function(x, y, alpha = 0.05) {
    .Call('artool_t_test', PACKAGE = 'artool', x, y, alpha)
}

anova_test <- function(treatment, response, K, alpha = 0.05) {
    .Call('artool_anova_test', PACKAGE = 'artool', treatment, response, K, alpha)
}

